title: Temptare
description: CSC-475 (Seminar in Computer Science) Project
theme: just-the-docs

url: https://joshberger5.github.io/Temptare

aux_links:
  GitHub: https://github.com/joshberger5/Temptare
